import { db } from '@/db';
import { contracts, invoices, handovers } from '@/db/schema';
import { eq } from 'drizzle-orm';
import { ShieldCheck, ShieldX } from 'lucide-react';
import { BrandMark } from '@/components/icons';
export const dynamic='force-dynamic';
export default async function VerifyPage({searchParams}:{searchParams:Promise<{id?:string}>}){const {id}=await searchParams;let document:{number:string;type:string}|null=null;if(id&&/^[0-9a-f-]{36}$/i.test(id)){const [invoice]=await db.select({number:invoices.invoiceNumber}).from(invoices).where(eq(invoices.id,id)).limit(1);if(invoice)document={...invoice,type:'Faktur Tagihan'};if(!document){const [handover]=await db.select({number:handovers.documentNumber}).from(handovers).where(eq(handovers.id,id)).limit(1);if(handover)document={...handover,type:'Berita Acara Serah Terima'};}if(!document){const [contract]=await db.select({number:contracts.contractNumber}).from(contracts).where(eq(contracts.id,id)).limit(1);if(contract)document={number:contract.number.replace('KTR','SPH'),type:'Surat Penawaran Harga'};}}
 return <main className="verify-page"><div className="brand"><BrandMark/><div className="brand-copy"><div>HEAVY<span>OPS</span><span className="brand-dot">.</span></div><small>Verifikasi Dokumen Digital</small></div></div><section className="panel verify-card"><span className="verify-icon">{document?<ShieldCheck size={32}/>:<ShieldX size={32}/>}</span><h1>{document?'Dokumen Terverifikasi':'Dokumen Tidak Ditemukan'}</h1><p>{document?'Nomor dokumen ini terdaftar pada sistem operasional PT Penyewaan Alat Berat.':'Tautan tidak valid atau dokumen belum terdaftar. Hubungi pihak penerbit untuk konfirmasi.'}</p>{document&&<div className="verify-details">{document.type}<b>{document.number}</b></div>}<small>Untuk melindungi kerahasiaan perusahaan, rincian keuangan dan data klien tidak ditampilkan pada halaman ini. Verifikasi ini mengonfirmasi pencatatan dokumen, bukan tanda tangan digital tersertifikasi.</small></section></main>;
}
