'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, PieChart, Pie, Cell } from 'recharts';
import { ArrowUpRight, ArrowRight, CalendarDays, ChevronDown, Download, FileText, CircleDollarSign, ReceiptText, MoreHorizontal, CircleCheck, Clock3, TriangleAlert, MapPin, ClipboardCheck, Plus, Activity } from 'lucide-react';
import { EquipmentIcon } from './icons';
import { Button } from './ui/button';
import type { WorkspaceData } from '@/lib/data';
import { money, shortMoney, labels, dateLabel } from '@/lib/format';
export function Badge({status}:{status:string}){return <span className={`status-badge status-${status}`}><i/>{labels[status]||status}</span>;}
export function Overview({data}:{data:WorkspaceData}) {
 const [range,setRange]=useState('6');const [monthOffset,setMonthOffset]=useState('0');const [fleetMenu,setFleetMenu]=useState(false);
 const now=new Date();const selected=new Date(now.getFullYear(),now.getMonth()+Number(monthOffset),1);
 const monthKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
 const revenue=(d:Date)=>data.invoices.filter(i=>i.issueDate.startsWith(monthKey(d))).reduce((sum,i)=>sum+Number(i.totalAmount),0);
 const monthRevenue=revenue(selected),previousRevenue=revenue(new Date(selected.getFullYear(),selected.getMonth()-1,1));
 const growth=previousRevenue?((monthRevenue-previousRevenue)/previousRevenue*100):0;
 const chartData=Array.from({length:Number(range)},(_,i)=>{const date=new Date(selected.getFullYear(),selected.getMonth()-Number(range)+1+i,1);return {name:date.toLocaleDateString('id-ID',{month:'short'}),current:revenue(date)/1e6,previous:revenue(new Date(date.getFullYear(),date.getMonth()-1,1))/1e6};});
 const statusData=[{name:'Disewa',value:data.fleet.filter(f=>f.status==='renting').length,color:'#f47727',status:'renting'},{name:'Tersedia',value:data.fleet.filter(f=>f.status==='available').length,color:'#50a885',status:'available'},{name:'Perawatan',value:data.fleet.filter(f=>f.status==='maintenance').length,color:'#efbf5b',status:'maintenance'},{name:'Dalam Mobilisasi',value:data.fleet.filter(f=>f.status==='in_transit').length,color:'#7998bc',status:'in_transit'}];
 const unpaid=data.invoices.filter(i=>i.status!=='paid');const overdue=unpaid.filter(i=>i.dueDate<now.toISOString().slice(0,10)||i.status==='overdue');
 const expiring=data.fleet.filter(f=>[f.sikoExpiry,f.insuranceExpiry].some(d=>d&&new Date(d).getTime()<=Date.now()+30*86400000));
 const recent=[...data.fleet].sort((a,b)=>Number(a.unitCode.split('-')[1])-Number(b.unitCode.split('-')[1])).slice(0,5);
 const totalPeriod=chartData.reduce((a,d)=>a+d.current,0)*1e6;
 return <div className="overview page-enter"><div className="page-heading"><div><div className="eyebrow"><span/>PUSAT KENDALI OPERASIONAL</div><h1>Dasbor Utama</h1><p>Selamat datang kembali, <b>{data.user.fullName.split(' ')[0]}</b>. Berikut ringkasan operasional Anda hari ini.</p></div><div className="page-heading-actions"><Button variant="outline" asChild><a href="/api/report"><Download size={16}/>Unduh Laporan</a></Button></div></div>
 <div className="section-toolbar"><div><span className="live-dot"/>Ringkasan operasional <span className="muted toolbar-date">· {dateLabel(now)}</span></div><label className="date-select"><CalendarDays size={15}/><select value={monthOffset} onChange={e=>setMonthOffset(e.target.value)} aria-label="Pilih periode ringkasan"><option value="0">{now.toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</option><option value="-1">{new Date(now.getFullYear(),now.getMonth()-1,1).toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</option><option value="-2">{new Date(now.getFullYear(),now.getMonth()-2,1).toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</option></select><ChevronDown size={13}/></label></div>
 <div className="metrics-grid"><Metric title="Total Armada" value={String(data.fleet.length)} suffix="unit" icon={<EquipmentIcon/>} tone="orange" foot={<><span className="green"><ArrowUpRight size={13}/>{statusData[1].value} unit tersedia</span><span>siap disewakan</span></>}/><Metric title="Unit Sedang Disewa" value={String(statusData[0].value)} suffix="unit" icon={<Activity size={21}/>} tone="green" foot={<><span className="green"><ArrowUpRight size={13}/>{data.fleet.length?Math.round(statusData[0].value/data.fleet.length*100):0}% utilisasi</span><span>dari total armada</span></>}/><Metric title="Pendapatan Bulan Ini" value={shortMoney(monthRevenue)} icon={<CircleDollarSign size={22}/>} tone="blue" foot={<><span className={growth>=0?'green':'red'}><ArrowUpRight size={13}/>{Math.abs(growth).toLocaleString('id-ID',{maximumFractionDigits:1})}%{growth<0?' turun':''}</span><span>dari bulan lalu</span></>}/><Metric title="Tagihan Belum Lunas" value={String(unpaid.length)} suffix="tagihan" icon={<ReceiptText size={21}/>} tone="amber" foot={<><span className="amber-text"><Clock3 size={13}/>{overdue.length} jatuh tempo</span><Link href="/dashboard/invoices">Lihat tagihan <ArrowUpRight size={12}/></Link></>}/></div>
 <div className="analytics-grid"><section className="panel revenue-panel"><div className="panel-header"><div><h2>Tren Pendapatan</h2><p>Pantau pertumbuhan pendapatan sewa Anda.</p></div><label className="small-select"><select value={range} onChange={e=>setRange(e.target.value)} aria-label="Periode grafik pendapatan"><option value="6">6 bulan terakhir</option><option value="12">12 bulan terakhir</option><option value="3">3 bulan terakhir</option></select><ChevronDown size={13}/></label></div><div className="revenue-summary"><div><strong>{money(totalPeriod)}</strong><span>Total pendapatan periode ini</span></div><div className="chart-legend"><span><i className="orange-dot"/>Pendapatan</span><span><i className="gray-dot"/>Bulan sebelumnya</span></div></div><div className="revenue-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{top:15,right:14,bottom:0,left:-20}}><defs><linearGradient id="revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f47727" stopOpacity={0.2}/><stop offset="100%" stopColor="#f47727" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e9e9e7"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:'#959593',fontSize:11}} dy={8}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#959593',fontSize:10}} tickFormatter={v=>`${v} jt`} tickCount={5}/><Tooltip contentStyle={{border:'1px solid #e9e8e5',borderRadius:10,fontSize:12,boxShadow:'0 6px 24px #0000000a'}} formatter={(value,name)=>[money(Number(value)*1e6),name==='current'?'Pendapatan':'Bulan sebelumnya']}/><Area isAnimationActive={false} type="monotone" dataKey="previous" stroke="#c8cece" strokeWidth={2} strokeDasharray="5 5" fill="transparent"/><Area isAnimationActive={false} type="monotone" dataKey="current" stroke="#f47727" strokeWidth={3} fill="url(#revenue-fill)" activeDot={{r:5,stroke:'#fff',strokeWidth:3}}/></AreaChart></ResponsiveContainer></div><div className="chart-footer"><span><span className="live-dot"/>Berdasarkan tagihan yang diterbitkan</span><Link href="/dashboard/invoices">Lihat detail pendapatan <ArrowRight size={13}/></Link></div></section>
 <section className="panel fleet-status-panel"><div className="panel-header"><div><h2>Status Armada</h2><p>Distribusi ketersediaan alat berat.</p></div><Link href="/dashboard/fleet" className="icon-button" aria-label="Lihat detail status armada"><MoreHorizontal size={20}/></Link></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={statusData} dataKey="value" innerRadius={69} outerRadius={89} startAngle={90} endAngle={-270} stroke="#fff" strokeWidth={4} cornerRadius={4}>{statusData.map(s=><Cell key={s.name} fill={s.color}/>)}</Pie><Tooltip formatter={(v,n)=>[`${v} unit`,n]} contentStyle={{borderRadius:8,fontSize:12}}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{data.fleet.length}</strong><span>Total unit</span></div></div><div className="status-legend">{statusData.map(s=><Link key={s.status} href={`/dashboard/fleet?status=${s.status}`}><span><i style={{background:s.color}}/>{s.name}</span><b>{s.value} <small>unit</small></b><span className="status-percent">{data.fleet.length?Math.round(s.value/data.fleet.length*100):0}%</span></Link>)}</div><div className="utilization"><span>Utilisasi armada</span><b>{data.fleet.length?Math.round(statusData[0].value/data.fleet.length*100):0}%<ArrowUpRight size={13}/></b><div><i style={{width:`${data.fleet.length?statusData[0].value/data.fleet.length*100:0}%`}}/></div></div></section></div>
 {expiring.length>0&&<Link href="/dashboard/fleet?filter=expiring" className="expiry-banner"><span className="expiry-icon"><TriangleAlert size={18}/></span><div><b>Dokumen armada perlu diperhatikan</b><span>{expiring.length} unit memiliki SIKO atau asuransi yang akan berakhir dalam 30 hari.</span></div><span className="expiry-link">Periksa dokumen <ArrowRight size={15}/></span></Link>}
 <div className="operations-grid"><section className="panel fleet-overview"><div className="panel-header"><div><h2>Ringkasan Armada</h2><p>Status terkini unit alat berat Anda.</p></div><Link className="text-link" href="/dashboard/fleet">Lihat semua <ArrowRight size={14}/></Link></div><div className="table-scroll"><table><thead><tr><th>UNIT ALAT BERAT</th><th>LOKASI SAAT INI</th><th>STATUS</th><th/></tr></thead><tbody>{recent.map(f=><tr key={f.id}><td><Link className="unit-cell" href={`/dashboard/fleet?q=${f.unitCode}`}><span className="unit-icon"><EquipmentIcon width={24} height={24}/></span><span><b>{f.brandModel}</b><small>{f.unitCode} <span>·</span> {f.category}</small></span></Link></td><td><span className="location-cell"><MapPin size={13}/>{f.currentLocation}</span></td><td><Badge status={f.status}/></td><td><Link href={`/dashboard/fleet?q=${f.unitCode}`} className="icon-button" aria-label={`Lihat ${f.unitCode}`}><ChevronDown size={15} className="rotate-arrow"/></Link></td></tr>)}</tbody></table></div><div className="table-footer"><span>Menampilkan {recent.length} dari {data.fleet.length} unit</span><Link href="/dashboard/fleet?new=1"><Plus size={14}/>Tambah unit</Link></div></section>
 <section className="panel activity-panel"><div className="panel-header"><div><h2>Aktivitas Terbaru</h2><p>Perkembangan operasional terkini.</p></div><Clock3 size={18} className="muted"/></div><div className="activity-list">{data.timesheets[0]&&<ActivityItem icon={<ClipboardCheck size={16}/>} tone="green" title="Catatan kerja telah dicatat" text={`${data.timesheets.filter(t=>t.status==='pending').length} catatan menunggu persetujuan operasional.`} time={dateLabel(data.timesheets[0].date)} href="/dashboard/timesheets"/>}{data.invoices[0]&&<ActivityItem icon={<ReceiptText size={16}/>} tone="orange" title="Tagihan sewa diterbitkan" text={`${data.invoices[0].invoiceNumber} · ${money(data.invoices[0].totalAmount)}`} time={dateLabel(data.invoices[0].issueDate)} href="/dashboard/invoices"/>}{data.handovers[0]&&<ActivityItem icon={<EquipmentIcon width={17} height={17}/>} tone="blue" title="Serah terima unit tercatat" text="Pemeriksaan dan serah terima unit telah didokumentasikan." time={dateLabel(data.handovers[0].date)} href="/dashboard/bast"/>}{data.contracts[0]&&<ActivityItem icon={<FileText size={16}/>} tone="purple" title="Kontrak sewa aktif" text={`${data.contracts[0].contractNumber} siap untuk operasional.`} time={dateLabel(data.contracts[0].startDate)} href="/dashboard/contracts"/>}{!data.contracts.length&&<p className="empty-inline">Belum ada aktivitas. Mulai dengan menambahkan armada dan klien.</p>}</div><Link className="activity-footer" href="/dashboard/timesheets">Lihat catatan operasional <ArrowRight size={14}/></Link></section></div>
 <div className="dashboard-bottom-note"><CircleCheck size={14}/><span>Seluruh data terhubung. Keputusan lebih tepat, operasional lebih efisien.</span></div>
 </div>;
}
function Metric({title,value,suffix,icon,tone,foot}:{title:string;value:string;suffix?:string;icon:React.ReactNode;tone:string;foot:React.ReactNode}){return <section className="metric-card"><div className="metric-top"><span>{title}</span><span className={`metric-icon ${tone}`}>{icon}</span></div><div className="metric-value">{value}<small>{suffix}</small></div><div className="metric-foot">{foot}</div></section>;}
function ActivityItem({icon,tone,title,text,time,href}:{icon:React.ReactNode;tone:string;title:string;text:string;time:string;href:string}){return <Link href={href} className="activity-item"><span className={`activity-icon ${tone}`}>{icon}</span><div><b>{title}</b><p>{text}</p><small>{time}</small></div></Link>;}
