'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState, useEffect, useRef } from 'react';
import { LayoutDashboard, UsersRound, FileText, ClipboardList, ClipboardCheck, ReceiptText, Settings2, Search, Bell, ChevronDown, ChevronRight, ChevronsLeft, PanelLeftOpen, CircleHelp, ArrowUpRight, X, LogOut, Home, Check, Menu } from 'lucide-react';
import { EquipmentIcon, BrandMark } from './icons';
import { Modal } from './ui/dialog';
import { signOut } from '@/app/actions';
import { labels, dateLabel } from '@/lib/format';
import type { WorkspaceData } from '@/lib/data';
export const navigation=[{path:'/dashboard',label:'Dasbor Utama',icon:LayoutDashboard},{path:'/dashboard/fleet',label:'Armada Alat Berat',icon:EquipmentIcon},{path:'/dashboard/clients',label:'Data Klien',icon:UsersRound},{path:'/dashboard/contracts',label:'Kontrak Sewa',icon:FileText},{path:'/dashboard/timesheets',label:'Timesheet Harian',icon:ClipboardList},{path:'/dashboard/bast',label:'BAST',icon:ClipboardCheck},{path:'/dashboard/invoices',label:'Penagihan',icon:ReceiptText}];
export function Shell({data,children}:{data:WorkspaceData;children:React.ReactNode}){
 const pathname=usePathname();const [collapsed,setCollapsed]=useState(false);const [mobile,setMobile]=useState(false);const [query,setQuery]=useState('');const [notifications,setNotifications]=useState(false);const [profile,setProfile]=useState(false);const [help,setHelp]=useState(false);
 const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==='k'){event.preventDefault();searchRef.current?.focus();}if(event.key==='Escape'){setQuery('');setNotifications(false);setProfile(false);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 const current=navigation.find(n=>n.path===pathname)||navigation.find(n=>n.path!=='/dashboard'&&pathname.startsWith(n.path));
 const pending=data.timesheets.filter(t=>t.status==='pending').length;
 const unpaid=data.invoices.filter(i=>i.status!=='paid').length;
 const expiring=data.fleet.filter(f=>[f.sikoExpiry,f.insuranceExpiry].some(d=>d&&new Date(d).getTime()<=Date.now()+30*86400000));
 const results=[...navigation.map(n=>({label:n.label,sub:'Menu ruang kerja',path:n.path})),...data.fleet.map(f=>({label:`${f.unitCode} · ${f.brandModel}`,sub:'Armada Alat Berat',path:`/dashboard/fleet?q=${encodeURIComponent(f.unitCode)}`})),...data.clients.map(c=>({label:c.companyName,sub:'Data Klien',path:`/dashboard/clients?q=${encodeURIComponent(c.companyName)}`})),...data.contracts.map(c=>({label:c.contractNumber,sub:'Kontrak Sewa',path:`/dashboard/contracts?q=${encodeURIComponent(c.contractNumber)}`}))].filter(r=>r.label.toLowerCase().includes(query.toLowerCase())).slice(0,7);
 return <div className={`app-shell ${collapsed?'sidebar-collapsed':''}`}>
 {mobile&&<div className="mobile-backdrop" onClick={()=>setMobile(false)}/>}
 <aside className={`sidebar ${mobile?'mobile-open':''}`}><Link className="brand" href="/dashboard"><BrandMark/><div className="brand-copy"><div>HEAVY<span>OPS</span><span className="brand-dot">.</span></div><small>Sistem Manajemen Rental</small></div></Link>
 <div className="workspace-label"><span>RUANG KERJA</span><button className="icon-button collapse-button" aria-label="Ciutkan menu" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={16}/>:<ChevronsLeft size={16}/>}</button></div>
 <nav className="navigation">{navigation.map((n,i)=>{const active=pathname===n.path||(n.path!=='/dashboard'&&pathname.startsWith(n.path));return <Link href={n.path} className={`nav-item ${active?'active':''}`} key={n.path} title={n.label} onClick={()=>setMobile(false)}><n.icon width={19} height={19}/><span>{n.label}</span>{i===4&&pending>0&&<b className="nav-count">{pending}</b>}{i===6&&unpaid>0&&<b className="nav-count plain">{unpaid}</b>}</Link>;})}</nav>
 <div className="nav-divider"/><div className="workspace-label settings-label"><span>LAINNYA</span></div><Link href="/dashboard/settings" className={`nav-item ${pathname==='/dashboard/settings'?'active':''}`} onClick={()=>setMobile(false)} title="Pengaturan"><Settings2 size={19}/><span>Pengaturan</span></Link>
 <div className="sidebar-bottom"><div className="help-card"><span className="help-icon"><CircleHelp size={20}/></span><h4>Butuh bantuan?</h4><p>Tim kami siap membantu<br/>operasional Anda.</p><button onClick={()=>setHelp(true)}>Hubungi Dukungan <ArrowUpRight size={15}/></button></div><div className="system-status"><span/>Sistem beroperasi normal</div><div className="sidebar-copyright">© {new Date().getFullYear()} HeavyOps <span>v1.0</span></div></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Buka menu" onClick={()=>setMobile(true)}><Menu size={21}/></button><Home size={16}/><span>Ruang kerja</span><ChevronRight size={13}/><b>{current?.label||(pathname.includes('settings')?'Pengaturan':'Dasbor Utama')}</b></div><div className="header-actions"><div className="global-search"><Search size={16}/><input ref={searchRef} placeholder="Cari di ruang kerja..." value={query} onChange={e=>setQuery(e.target.value)} aria-label="Cari di ruang kerja"/><kbd>⌘ K</kbd>{query&&<div className="search-results"><div className="popover-label">HASIL PENCARIAN<button aria-label="Tutup pencarian" onClick={()=>setQuery('')}><X size={14}/></button></div>{results.length?results.map(r=><Link key={r.label} href={r.path} onClick={()=>setQuery('')}><Search size={15}/><div>{r.label}<small>{r.sub}</small></div><ChevronRight size={14}/></Link>):<p>Tidak ada hasil ditemukan.</p>}</div>}</div><div className="header-popover-wrap"><button className={`notification-button icon-button ${notifications?'selected':''}`} aria-label="Lihat pemberitahuan" onClick={()=>{setNotifications(!notifications);setProfile(false);}}><Bell size={20}/>{(pending>0||expiring.length>0)&&<i/>}</button>{notifications&&<div className="header-popover notifications"><h4>Pemberitahuan <span>{pending+expiring.length}</span></h4><Link href="/dashboard/timesheets" onClick={()=>setNotifications(false)}><span className="activity-icon orange"><ClipboardList size={18}/></span><div><b>{pending} catatan menunggu persetujuan</b><p>Periksa catatan kerja harian operator.</p></div></Link><Link href="/dashboard/fleet?filter=expiring" onClick={()=>setNotifications(false)}><span className="activity-icon amber"><FileText size={18}/></span><div><b>{expiring.length} dokumen perlu diperhatikan</b><p>SIKO atau asuransi akan berakhir.</p></div></Link></div>}</div><div className="header-separator"/><div className="header-popover-wrap"><button className="profile-button" onClick={()=>{setProfile(!profile);setNotifications(false);}}><span className="avatar">{data.user.fullName.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span className="profile-copy"><b>{data.user.fullName}</b><small>{labels[data.user.role]}</small></span><ChevronDown size={15}/></button>{profile&&<div className="header-popover profile-menu"><b>{data.user.fullName}</b><p>{data.user.email}</p>{data.user.preview&&<span className="preview-label">Mode pratinjau · Data demonstrasi</span>}<Link href="/dashboard/settings" onClick={()=>setProfile(false)}><Settings2 size={16}/>Pengaturan akun</Link><form action={signOut}><button><LogOut size={16}/>Keluar dari sistem</button></form></div>}</div></div></header>
 <main className="page-content">{children}</main><footer className="main-footer"><span>© {new Date().getFullYear()} PT Penyewaan Alat Berat. Seluruh hak dilindungi.</span><span><span className="footer-dot"/>{data.user.preview?'Lingkungan pratinjau':'Koneksi aman'}<i/>Waktu Indonesia Barat (WIB)</span></footer></div>
 <Modal open={help} onOpenChange={setHelp} title="Pusat Bantuan HeavyOps" description="Dukungan untuk kelancaran operasional Anda."><div className="help-content"><div className="info-callout"><CircleHelp size={20}/><p>Untuk kendala akses, perubahan hak pengguna, atau pertanyaan operasional, silakan hubungi administrator perusahaan.</p></div><h4>Hubungi tim operasional</h4><a href={`mailto:${data.settings.email}`}>{data.settings.email||'Surel belum diatur'}</a><a href={`tel:${data.settings.phone}`}>{data.settings.phone||'Telepon belum diatur'}</a><hr/><h4>Panduan singkat</h4><p>1. Daftarkan unit dan klien pada menu data utama.</p><p>2. Buat kontrak sewa untuk unit yang tersedia.</p><p>3. Catat jam kerja dan ajukan persetujuan.</p><p>4. Terbitkan tagihan dari jam kerja yang disetujui.</p><small>Terakhir diperbarui: {dateLabel(new Date())}</small></div></Modal>
 </div>;
}
